import Sidebar from "@/components/layouts/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore - Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            {children}
        </div>
    );
}