import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore - Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <h1>Admin</h1>
                {children}
            </body>
        </html>
    );
}