import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore - Seller",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <h1>Seller</h1>
            {children}
        </div>
    );
}