import { AppSidebar } from "@/components/app-sidebar";
import Sidebar from "@/components/layouts/Sidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore - Seller",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <SidebarProvider>
                <AppSidebar />
                <SidebarInset>
                    <header className="flex h-16 shrink-0 items-center gap-2 border-b">
                        <div className="flex items-center gap-2 px-3">
                            <SidebarTrigger />
                        </div>
                    </header>
                    {children}
                    <Toaster position="top-center" />
                </SidebarInset>
            </SidebarProvider>
        </div>
    );
}