import Navbar from "@/components/layouts/Navbar";
import { CartOrdersNavbar } from "@/components/orders/CartOrderNav";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div className="mt-20">
            <CartOrdersNavbar />
            {children}
        </div>
    );
}