import AppFooter from "@/components/layouts/AppFooter";
import Navbar from "@/components/layouts/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div>
            <Navbar />
            <div className="mt-16">
                {children}
            </div>
            <AppFooter />
        </div>
    );
}