import Navbar from "@/components/layouts/Navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "MediStore",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div>
            <Navbar />
            {children}
        </div>
    );
}